### PR TITLE
chore(release): 1.1.0

### PR DESCRIPTION
**Pull request by rabelloo**
## Purpose

Merge minor version in.

### CODE REVIEW

**Comment by josokinas** [comment]
Why would you want to merge this back in?

Based on our guide [only major release needs a merge back](https://github.com/onfido/castor-icons/blob/main/CONTRIBUTING.md#release-a-major-version-example), but [minor and patch does not](https://github.com/onfido/castor-icons/blob/main/CONTRIBUTING.md#release-a-minorpatch-version-example).

**Comment by rabelloo** [comment]
So that:
- the next release version is automatically and correctly picked up
- the repository's home page `CHANGELOG.md` is up to date

We might want to rethink our guide, based on the above, it makes sense to release on `main` and then cut the release branch, which only needs cherry-picked commits for hotfixes.

What do you think?

**Comment by josokinas** [comment]
>  the next release version is automatically and correctly picked up

But I guess this would only be for minor, excluding patches correct? Also, how would it be in case of e.g. `1.2.0` bump when currently latest is `2.0.0`?

> the repository's home page `CHANGELOG.md` and `package.json` are up to date

I guess having `CHANGELOG.md` to reflect changes is OK, but then yet again not very clear to me the situation of multiple major versions. Do we only have bugfixes in previous versions when the next major released?

> It makes sense to release on `main` and then cut the release branch, which only needs cherry-picked commits for hotfixes.

Yet again not entirely sure, unless having release branch per major version is not that good of idea?

P.S. I believe that the log generator was a little wrong, I just noticed that the license fix [was already applied _before_ the initial release](https://github.com/onfido/castor-icons/commits/release/1.x.x).

**Comment by rabelloo** [comment]
I guess the point of major release branches is to retroactively apply hotfixes:

image

For minors and patches it makes total sense to simply fast-forward on the trunk - `main`.

We always need the latest version on `main`, otherwise we can't auto-gen the next version:

image

**Comment by rabelloo** [comment]
> P.S. I believe that the log generator was a little wrong, I just noticed that the license fix was already applied before the initial release.

That happened because we were missing a tag, I created it afterwards but too late.
I'll open another MR to fix the changelog.

**Review by josokinas — APPROVED** [review]

**Pull request merged**
